-- AlterTable
ALTER TABLE "DraftPlugin" ADD COLUMN     "envVars" JSONB NOT NULL DEFAULT E'[]',
ADD COLUMN     "maxHeight" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN     "maxWidth" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN     "minHeight" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "minWidth" INTEGER NOT NULL DEFAULT 1,
ALTER COLUMN "icon" DROP NOT NULL;
